version: "3.4"

services:
  php:
    container_name: php
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"

  sqs:
    container_name: sqs
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"